spring:
  application:
    name: file-upload-rustfs

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        
storage:
  rustfs:
    endpoint: ${RUSTFS_URL:http://localhost:9000}
    region: ${RUSTFS_REGION:us-east-1}
    access-key: ${RUSTFS_ACCESS_KEY:SYSADM}
    secret-key: ${RUSTFS_SECRET_KEY:SYS168}
    bucket: ${RUSTFS_BUCKET:uploads}
